// Cloudflare Worker entry point for the Lowball multiplayer relay.
// Routes WebSocket upgrade requests to LowballRelayDO instances addressed
// by room code (REQ-001, REQ-007, REQ-011).
//
// URL format: /room/<ROOMCODE>
// Creates a new DO instance when a host uses "create" flow (a room code is
// generated by this Worker and the client is redirected to /room/<CODE>).
//
// This file has no scoring logic — all game logic lives in room.ts (the DO).

import { LowballRelayDO } from "./room.ts";

export { LowballRelayDO };

// Cloudflare Worker types — provided by @cloudflare/workers-types
export interface Env {
  LOWBALL_RELAY: DurableObjectNamespace;
  RELAY_BASE_URL?: string; // optional: used to construct invite links shown in DEPLOYMENT.md
}

/** Max display name length, mirroring the spec (REQ-005). */
const MAX_NAME_LEN = 20;

/**
 * Validate room code format: exactly 6 uppercase alphanumeric chars.
 * Rejects on the Worker before routing to a DO.
 */
function isValidRoomCode(code: string): boolean {
  return /^[A-Z0-9]{6}$/.test(code);
}

/** Generate a candidate 6-char room code using the Worker's crypto (REQ-001). */
function generateCode(): string {
  const bytes = new Uint8Array(4);
  crypto.getRandomValues(bytes);
  const n = (bytes[0]! * 16777216 + bytes[1]! * 65536 + bytes[2]! * 256 + bytes[3]!) >>> 0;
  return n.toString(36).toUpperCase().padStart(6, "0").slice(-6);
}

/**
 * Check whether a DO stub for a given code has an active session.
 * We use a lightweight HTTP probe to the DO rather than storage, keeping
 * the DO itself storage-free (REQ-056).
 * Returns true when the room exists and has capacity.
 */
async function roomExists(env: Env, code: string): Promise<boolean> {
  try {
    const id = env.LOWBALL_RELAY.idFromName(code);
    const stub = env.LOWBALL_RELAY.get(id);
    const res = await stub.fetch(`https://relay/probe/${code}`);
    return res.status === 200;
  } catch {
    return false;
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    // CORS preflight (for development convenience)
    if (request.method === "OPTIONS") {
      return new Response(null, {
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Headers": "Content-Type",
        },
      });
    }

    // -----------------------------------------------------------------------
    // POST /create — generate a unique room code and return it as JSON.
    // The client then immediately opens a WebSocket to /room/<code>.
    // This is a separate step so the client can construct the invite link
    // before opening the WS (REQ-038).
    // -----------------------------------------------------------------------
    if (request.method === "POST" && path === "/create") {
      let code = generateCode();
      // REQ-002: collision retry (up to 5 attempts)
      for (let attempt = 0; attempt < 5; attempt++) {
        if (!(await roomExists(env, code))) break;
        code = generateCode();
      }
      return Response.json({ roomCode: code }, {
        headers: { "Access-Control-Allow-Origin": "*" },
      });
    }

    // -----------------------------------------------------------------------
    // GET /room/<code> — WebSocket upgrade, routed to the room DO.
    // REQ-007: unknown code → ROOM_NOT_FOUND.
    // REQ-006: 5th join → ROOM_FULL (handled inside the DO).
    // REQ-011: join-after-start → ROOM_IN_PROGRESS (handled inside the DO).
    // -----------------------------------------------------------------------
    const roomMatch = path.match(/^\/room\/([A-Z0-9]{1,10})$/i);
    if (roomMatch) {
      const rawCode = roomMatch[1]!.toUpperCase();

      if (!isValidRoomCode(rawCode)) {
        return new Response(JSON.stringify({ error: "ROOM_NOT_FOUND" }), {
          status: 404,
          headers: { "Content-Type": "application/json" },
        });
      }

      // Validate display name from header or query param (supplied before WS upgrade)
      const displayName = request.headers.get("X-Display-Name") ?? url.searchParams.get("name") ?? "";
      const trimmed = displayName.trim();
      if (trimmed.length === 0 || trimmed.length > MAX_NAME_LEN) {
        // REQ-005: close with INVALID_NAME — for HTTP pre-upgrade use 400
        return new Response(JSON.stringify({ error: "INVALID_NAME" }), {
          status: 400,
          headers: { "Content-Type": "application/json" },
        });
      }

      // Route to the DO by room code name
      const id = env.LOWBALL_RELAY.idFromName(rawCode);
      const stub = env.LOWBALL_RELAY.get(id);
      return stub.fetch(request);
    }

    return new Response("Not found", { status: 404 });
  },
};
