#!/usr/bin/env bash
# quality-gate.sh — runs typecheck + unit tests + coverage + e2e; non-zero exit on any failure.
#
# Usage:
#   bash .bob/scripts/quality-gate.sh [--fast]
#
#   --fast   skip coverage and e2e (typecheck + unit tests only)
#
# Generated by /start-project Phase 5 for the cic-games repo.
# This script is NOT executed by the skill. Run it yourself.

set -euo pipefail

FAST=0
for arg in "$@"; do
  case "$arg" in
    --fast) FAST=1 ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

FAILED=()

step() {
  local name="$1"; shift
  echo ""
  echo "=== $name ==="
  if "$@"; then
    echo "--- $name: PASS"
  else
    echo "--- $name: FAIL"
    FAILED+=("$name")
  fi
}

# --- Stack detection -------------------------------------------------------
if [ ! -f package.json ]; then
  echo "quality-gate: no package.json at $REPO_ROOT" >&2
  exit 1
fi

# --- Gates -----------------------------------------------------------------
step "typecheck (tsc -b --noEmit)" npm run typecheck

step "unit tests (vitest run)" npm test

if [ "$FAST" -eq 0 ]; then
  step "coverage (vitest run --coverage)" npm run coverage
  step "e2e (playwright test)" npm run e2e
else
  echo ""
  echo "=== coverage + e2e: SKIPPED (--fast) ==="
fi

# --- Lowball-specific content gate ----------------------------------------
# The content pack is generated, not committed as source of truth. If the
# generator exists, regenerate and let its own fairness gate assert itself.
if [ -f tools/build-lowball.ts ]; then
  step "lowball content pack + fairness gate" npx tsx tools/build-lowball.ts
else
  echo ""
  echo "=== lowball content gate: SKIPPED (tools/build-lowball.ts not present yet) ==="
fi

# --- Summary ---------------------------------------------------------------
echo ""
echo "==================== SUMMARY ===================="
if [ "${#FAILED[@]}" -eq 0 ]; then
  echo "ALL GATES PASSED"
  exit 0
fi
echo "FAILED GATES (${#FAILED[@]}):"
for f in "${FAILED[@]}"; do echo "  - $f"; done
exit 1
