#!/usr/bin/env bash
# setup-env.sh — INFORMATIONAL ONLY. Prints the environment prerequisites for
# working on the lowball game in this repo. Does NOT install anything and does
# NOT execute any install command.
#
# Usage:
#   bash .bob/scripts/setup-env.sh [--check]
#
#   --check   probe the local toolchain and report versions found vs required
#
# Generated by /start-project Phase 5. Never auto-executed.

set -euo pipefail

CHECK=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    -h|--help) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

cat <<'INFO'
=============================================================
 lowball — environment prerequisites (informational)
=============================================================

TOOLCHAIN
  node        >= 20      (Vite 5 / Vitest 2 baseline)
  npm         >= 10
  tsx                    (already a devDependency; used by tools/build-*.ts)

INSTALL (run yourself; this script will not)
  npm install

BUILD-TIME DATA DEPENDENCY  <-- the one non-obvious prerequisite
  wordkit/vectors/glove.6B.50d.txt      163 MB, gitignored

  Required ONLY at content-build time. Never shipped to clients.
  Seven existing build tools already depend on it, plus tools/build-lowball.ts.
  Without it, `npm run gen:data:lowball` fails fast by design (REQ-043).

  The vectors provide the fine-grained frequency signal behind the panel score:
  GloVe's 400,000-word vocabulary is ordered by DESCENDING corpus frequency, so a
  word's line number is its frequency rank. Combined with SCOWL tiers from
  wordkit/data/en-GB/corpus.json (111,676 en-GB words), this yields the 0-100
  simulated panel score.

  IMPORTANT (REQ-053): that score is a DERIVED STATISTICAL MODEL, not a survey of
  real people. The UI must state "simulated panel of 100 - from corpus frequency"
  and must never imply real people were asked.

TOOLING GAPS recorded in NFR-WAIVERS.md
  axe-core    NOT yet a devDependency. Needed for the automated WCAG 2.1 AA scan
              that REQ-049..REQ-052 depend on. Playwright is already present.

ENVIRONMENT VARIABLES
  none required at runtime. The game is fully offline: no backend, no network
  calls beyond the precached content pack asset, no telemetry (REQ-055).

  For the SDLC tooling only (not the game):
    A2A_BEARER_TOKEN    required by the bob-sdlc-skills MCP server for
                        /spec-workflow and /start-project. Not needed to build,
                        test or run the game.

KEY COMMANDS
  npm run gen:data:lowball   generate public/lowball.json (add to package.json)
  npm test                   vitest run
  npm run typecheck          tsc -b --noEmit
  npm run e2e                playwright test
  npm run build              tsc -b && vite build
  bash .bob/scripts/quality-gate.sh          full gate
  bash .bob/scripts/validate-planning.sh     planning-pack completeness

INFO

if [ "$CHECK" -eq 1 ]; then
  echo "============================================================="
  echo " toolchain probe"
  echo "============================================================="
  probe() {
    local name="$1"; local cmd="$2"
    if command -v "${cmd%% *}" >/dev/null 2>&1; then
      printf "  %-12s %s\n" "$name" "$(eval "$cmd" 2>&1 | head -1)"
    else
      printf "  %-12s NOT FOUND\n" "$name"
    fi
  }
  probe node "node --version"
  probe npm  "npm --version"
  probe npx  "npx --version"
  probe git  "git --version"

  echo ""
  echo "  GloVe vectors:"
  GLOVE="$REPO_ROOT/wordkit/vectors/glove.6B.50d.txt"
  if [ -f "$GLOVE" ]; then
    printf "    PRESENT  %s (%s)\n" "$GLOVE" "$(du -h "$GLOVE" | cut -f1)"
  else
    printf "    MISSING  %s\n" "$GLOVE"
    echo "             content builds that need semantic/frequency data will fail fast"
  fi

  echo ""
  echo "  SCOWL corpus:"
  CORPUS="$REPO_ROOT/wordkit/data/en-GB/corpus.json"
  if [ -f "$CORPUS" ]; then
    printf "    PRESENT  %s (%s)\n" "$CORPUS" "$(du -h "$CORPUS" | cut -f1)"
  else
    printf "    MISSING  %s\n" "$CORPUS"
  fi

  echo ""
  echo "  node_modules:"
  if [ -d "$REPO_ROOT/node_modules" ]; then
    echo "    PRESENT"
  else
    echo "    MISSING — run 'npm install'"
  fi

  echo ""
  echo "  axe-core (NFR-001 prerequisite):"
  if [ -d "$REPO_ROOT/node_modules/axe-core" ]; then
    echo "    PRESENT"
  else
    echo "    MISSING — required for the automated accessibility gate"
  fi
fi
