#!/usr/bin/env bash
# validate-planning.sh — verifies the planning pack is complete for its complexity class.
#
# Usage:
#   bash .bob/scripts/validate-planning.sh [--branch <name>]
#
# Reads COMPLEXITY.json to determine which artifacts are required, then checks each
# exists and is non-empty. Exits non-zero if any required artifact is missing.
#
# Generated by /start-project Phase 5. Never auto-executed.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
BRANCH="$(git branch --show-current 2>/dev/null | sed 's/[^a-zA-Z0-9]/-/g' || echo main)"

while [ $# -gt 0 ]; do
  case "$1" in
    --branch) BRANCH="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

DOCS_DIR="$REPO_ROOT/.bob/docs/$BRANCH"

if [ ! -d "$DOCS_DIR" ]; then
  echo "validate-planning: no docs dir at $DOCS_DIR" >&2
  exit 1
fi

COMPLEXITY_FILE="$DOCS_DIR/COMPLEXITY.json"
if [ ! -f "$COMPLEXITY_FILE" ]; then
  echo "validate-planning: missing $COMPLEXITY_FILE" >&2
  exit 1
fi

CLASS="$(node -e "console.log(require('$COMPLEXITY_FILE').complexity_class)" 2>/dev/null || echo unknown)"
echo "complexity class: $CLASS"
echo "docs dir:         $DOCS_DIR"
echo ""

# Always-on artifacts (every complexity class)
REQUIRED=(
  COMPLEXITY.json
  USER-JOURNEYS.md
  GLOSSARY.md
  REQUIREMENTS.md
  TDD-STRATEGY.md
  TRACEABILITY-MATRIX.md
  VERIFICATION-REPORT.md
  PROJECT-PLAN.md
  IMPLEMENTATION-ROADMAP.md
  RISKS-AND-MITIGATIONS.md
)

# Complexity-gated additions
case "$CLASS" in
  trivial) ;;
  small)   REQUIRED+=(NFR-WAIVERS.md ARCHITECTURE.md) ;;
  medium|large)
    REQUIRED+=(NFR-WAIVERS.md ARCHITECTURE.md INTERFACES.md DATA-MODEL.md
               STATE-MACHINES.md ASSUMPTIONS.md PARALLEL-GROUPS.md
               CRITICAL-PATH.md INTEGRATION-TESTS.md)
    ;;
  *) echo "WARN: unrecognised complexity class '$CLASS'; checking always-on set only" ;;
esac

MISSING=()
EMPTY=()
for f in "${REQUIRED[@]}"; do
  if [ ! -e "$DOCS_DIR/$f" ]; then
    MISSING+=("$f")
  elif [ ! -s "$DOCS_DIR/$f" ]; then
    EMPTY+=("$f")
  fi
done

# AGENTS.md lands under the per-branch .bob/ subdir
if [ ! -s "$DOCS_DIR/.bob/AGENTS.md" ] && [ ! -s "$REPO_ROOT/.bob/AGENTS.md" ]; then
  MISSING+=(".bob/AGENTS.md")
fi

# Gherkin features
FEATURE_COUNT=0
if [ -d "$DOCS_DIR/features" ]; then
  FEATURE_COUNT="$(find "$DOCS_DIR/features" -name '*.feature' | wc -l | tr -d ' ')"
fi
[ "$FEATURE_COUNT" -eq 0 ] && MISSING+=("features/*.feature")

# Gates
GATE_COUNT=0
if [ -d "$DOCS_DIR/gates" ]; then
  GATE_COUNT="$(find "$DOCS_DIR/gates" -name '*.gate.json' | wc -l | tr -d ' ')"
fi

echo "artifacts required: ${#REQUIRED[@]}"
echo "feature files:      $FEATURE_COUNT"
echo "gate files:         $GATE_COUNT"
echo ""

# Atomicity carry-over: spec-workflow phase-3 gate must not be FAIL
ATOM_GATE="$DOCS_DIR/gates/phase-3.gate.json"
if [ -f "$ATOM_GATE" ]; then
  ATOM_RESULT="$(node -e "console.log(require('$ATOM_GATE').result)" 2>/dev/null || echo unknown)"
  echo "atomicity gate:     $ATOM_RESULT"
  case "$ATOM_RESULT" in
    FAIL) echo "ERROR: atomicity gate reports FAIL; planning pack is not valid" >&2; exit 1 ;;
  esac
else
  echo "WARN: no atomicity gate at $ATOM_GATE"
fi

echo ""
if [ "${#MISSING[@]}" -eq 0 ] && [ "${#EMPTY[@]}" -eq 0 ]; then
  echo "PLANNING PACK COMPLETE for class '$CLASS'"
  exit 0
fi
[ "${#MISSING[@]}" -gt 0 ] && { echo "MISSING (${#MISSING[@]}):"; for f in "${MISSING[@]}"; do echo "  - $f"; done; }
[ "${#EMPTY[@]}" -gt 0 ] && { echo "EMPTY (${#EMPTY[@]}):"; for f in "${EMPTY[@]}"; do echo "  - $f"; done; }
exit 1
